name: tasty_bytes_dbt_demo
config-version: 2

profile: tasty_bytes

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
    +on_schema_change: "sync_all_columns"
    
    tasty_bytes_dbt_demo:
        bronze:
            +materialized: view
        silver:
            +materialized: incremental